import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, Order, Quote, ThirdParty, InvoiceItem, OrderItem, QuoteItem } from '@prisma/client';

// Define types with relations
type InvoiceWithRelations = Invoice & { thirdParty: ThirdParty; items: InvoiceItem[] };
type OrderWithRelations = Order & { thirdParty: ThirdParty; items: (OrderItem & { product: { name: string } | null })[] };
type QuoteWithRelations = Quote & { thirdParty: ThirdParty; items: (QuoteItem & { product: { name: string } | null })[] };

const COMPANY_INFO = {
    name: "Akkademircelik ERP",
    address: "123 Industrial Zone",
    city: "Istanbul, Turkey",
    phone: "+90 555 123 4567",
    email: "info@akkademircelik.com",
};

const COLORS = {
    primary: [41, 128, 185] as [number, number, number], // #2980b9
    secondary: [127, 140, 141] as [number, number, number], // #7f8c8d
    text: [44, 62, 80] as [number, number, number], // #2c3e50
};

function addHeader(doc: jsPDF, title: string, id: string, date: Date) {
    const pageWidth = doc.internal.pageSize.width;

    // Company Logo/Name
    doc.setFontSize(20);
    doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
    doc.text(COMPANY_INFO.name, 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(COLORS.secondary[0], COLORS.secondary[1], COLORS.secondary[2]);
    doc.text(COMPANY_INFO.address, 14, 26);
    doc.text(COMPANY_INFO.city, 14, 30);
    doc.text(COMPANY_INFO.phone, 14, 34);
    doc.text(COMPANY_INFO.email, 14, 38);

    // Document Title & ID
    doc.setFontSize(24);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text(title, pageWidth - 14, 20, { align: 'right' });

    doc.setFontSize(12);
    doc.setTextColor(COLORS.secondary[0], COLORS.secondary[1], COLORS.secondary[2]);
    doc.text(`#${id.slice(-6).toUpperCase()}`, pageWidth - 14, 28, { align: 'right' });
    doc.text(new Date(date).toLocaleDateString(), pageWidth - 14, 34, { align: 'right' });
}

function addThirdPartyInfo(doc: jsPDF, thirdParty: ThirdParty, type: 'Bill To' | 'Ship To' | 'Prepared For' | 'Vendor' = 'Bill To') {
    doc.setFontSize(12);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text(type, 14, 55);

    doc.setFontSize(10);
    doc.setTextColor(COLORS.secondary[0], COLORS.secondary[1], COLORS.secondary[2]);
    doc.text(thirdParty.name, 14, 62);
    if (thirdParty.address) doc.text(thirdParty.address, 14, 66);
    if (thirdParty.phone) doc.text(thirdParty.phone, 14, 70);
    if (thirdParty.email) doc.text(thirdParty.email, 14, 74);
    if (thirdParty.taxId) doc.text(`Tax ID: ${thirdParty.taxId}`, 14, 78);
}

function addFooter(doc: jsPDF) {
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(COLORS.secondary[0], COLORS.secondary[1], COLORS.secondary[2]);
    doc.text("Thank you for your business!", 14, pageHeight - 10);
    doc.text(`Generated by Akkademircelik ERP on ${new Date().toLocaleString()}`, 14, pageHeight - 6);
}

export function generateInvoicePDF(invoice: InvoiceWithRelations) {
    const doc = new jsPDF();

    addHeader(doc, "INVOICE", invoice.id, invoice.issueDate);
    addThirdPartyInfo(doc, invoice.thirdParty);

    const tableColumn = ["Description", "Quantity", "Unit Price", "Total"];
    const tableRows: any[] = [];

    invoice.items.forEach((item: any) => {
        const itemData = [
            item.description,
            item.quantity,
            `$${item.unitPrice.toFixed(2)}`,
            `$${item.totalPrice.toFixed(2)}`
        ];
        tableRows.push(itemData);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 90,
        theme: 'striped',
        headStyles: { fillColor: COLORS.primary },
        styles: { fontSize: 10 },
    });

    // @ts-ignore
    const finalY = (doc as any).lastAutoTable.finalY || 90;

    doc.setFontSize(12);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text(`Total Amount: $${invoice.totalAmount.toFixed(2)}`, 14, finalY + 10);
    doc.text(`Paid Amount: $${invoice.paidAmount.toFixed(2)}`, 14, finalY + 16);
    doc.text(`Balance Due: $${(invoice.totalAmount - invoice.paidAmount).toFixed(2)}`, 14, finalY + 22);

    addFooter(doc);
    doc.save(`invoice_${invoice.id.slice(-6)}.pdf`);
}

export function generateQuotePDF(quote: QuoteWithRelations) {
    const doc = new jsPDF();

    addHeader(doc, "QUOTE", quote.id, quote.createdAt);
    addThirdPartyInfo(doc, quote.thirdParty, 'Prepared For');

    const tableColumn = ["Description", "Quantity", "Unit Price", "Total"];
    const tableRows: any[] = [];

    quote.items.forEach((item: any) => {
        const itemData = [
            item.product?.name || "Item",
            item.quantity,
            `$${item.unitPrice.toFixed(2)}`,
            `$${(item.quantity * item.unitPrice).toFixed(2)}`
        ];
        tableRows.push(itemData);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 90,
        theme: 'striped',
        headStyles: { fillColor: COLORS.primary },
        styles: { fontSize: 10 },
    });

    // @ts-ignore
    const finalY = (doc as any).lastAutoTable.finalY || 90;

    doc.setFontSize(12);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text(`Total Amount: $${quote.totalAmount.toFixed(2)}`, 14, finalY + 10);

    addFooter(doc);
    doc.save(`quote_${quote.id.slice(-6)}.pdf`);
}

export function generateOrderPDF(order: OrderWithRelations) {
    const doc = new jsPDF();

    const title = order.type === 'SALES' ? "SALES ORDER" : "PURCHASE ORDER";
    addHeader(doc, title, order.id, order.createdAt);
    addThirdPartyInfo(doc, order.thirdParty, order.type === 'SALES' ? 'Bill To' : 'Vendor');

    const tableColumn = ["Description", "Quantity", "Unit Price", "Total"];
    const tableRows: any[] = [];

    order.items.forEach((item: any) => {
        const itemData = [
            item.product?.name || "Item",
            item.quantity,
            `$${item.unitPrice.toFixed(2)}`,
            `$${(item.quantity * item.unitPrice).toFixed(2)}` // Calculate total price
        ];
        tableRows.push(itemData);
    });

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 90,
        theme: 'striped',
        headStyles: { fillColor: COLORS.primary },
        styles: { fontSize: 10 },
    });

    // @ts-ignore
    const finalY = (doc as any).lastAutoTable.finalY || 90;

    doc.setFontSize(12);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.text(`Total Amount: $${order.totalAmount.toFixed(2)}`, 14, finalY + 10);

    addFooter(doc);
    doc.save(`order_${order.id.slice(-6)}.pdf`);
}
